### ISSUE TITLE
Recovery word phrase is invalid

### ISSUE THREAD

**Issue by rioda-org** [mimblewimble/docs#15]
I presume, word phrase in recovery process should be entered as originaly presented, every word separated by space? I did copy paste of words, I've run a new node, synced and now I get this message "Recovery word phrase is invalid" when I run command "./grin wallet recover"
Any suggestions?
Should have saved damn files...

this is the error i get when trying to recover wallet
20190124 21:55:07.256 ERROR grin_wallet::command - Error recovering seed - IO error
Wallet command failed: IO error

**Comment by sesam** [comment]
@rioda-org Good you got it solved I presume? Otherwise there's the support chat that can give answers fairly quickly: https://gitter.im/grin_community/support
Another trick, and for anyone coming here later, sometimes `grin wallet check` is all you need. On the other hand it is good to practice doing backup and restore regularly.

**Comment by rioda-org** [comment]
The thing is, I've formated hdd that had my node and wallet. I've put up new node and wanted to "get back" my first wallet from seed words.
I used "grin wallet recover" command, but that is wrong, procedure is:
1. grin wallet init -r
2. grin wallet restore
i got mixed up in restore/recover terminology
