### ISSUE TITLE
How does a client connect to grin wallet?

### ISSUE THREAD

**Issue by leezijie** [mimblewimble/docs#19]
How does a client connect to grin wallet?

**Comment by Lalit15** [comment]
I am following steps mentioned in "How to: Run a Grin node on Google Cloud for free" but not able initiate wallet and sync it with node on Google cloud.
Will be great if someone from community can correct that doc and help explain clearly the steps to setup the wallet once the node has been configured. And if setting or variable has to be setup, kindly mention the set clearly so that there is no confusion

**Comment by jaramillobros** [comment]
agreed the step by step walk thru only work on floornet  not mainnet. we need a true mainnet walkthrough that shows how the wallet is connected and configured to sync with the node and listener.  please help

**Comment by cayblood** [comment]
Along these same lines, I'm setting up a wallet listener behind an elastic load balancer for easy SSL termination, but I can't set it up without knowing how to set up a health check on the wallet. It would be great if someone could document the wallet listening protocol so that I could set up a simple HTTP request that should return a 200 OK when the wallet is listening.
