### ISSUE TITLE
Question: Why does Grin uses files to send transactions?

### ISSUE THREAD

**Issue by igorgue** [mimblewimble/docs#20]
Is there a reason why the current way to transact doesn't have a concept of __address__? I might be missing something here, but looks quite cumbersome to get people to use it unless they're programmers.

In other words: Is this 1985?

**Comment by DavidBurkett** [comment]
The privacy that Grin provides requires interaction with the recipient to be able to build a transaction. There are folks like vault713 who have created ways to make it easier, but the short answer is yes, we're in 1985. But at least we're not in 1984, like Bitcoin. Big Brother has no power here :)

**Comment by sesam** [comment]
Why files?

1. it showcases the interactivity of MW transactions
2. you could do a tx over HTTPS or Keybase chat if you want
3. because we still need wallets to be built.

Something like the above might suit on the FAQ. Improvements?

@igorgue What grin info materials did you read before arriving here? Asking to figure out how to best improve docs.

**Comment by igorgue** [comment]
@sesam thanks for the answer!

I was reading this https://github.com/mimblewimble/docs/wiki/how-to-use-the-grin-wallet#sending-grins

I think, my question was that if there's something in the protocol that requires 2 online participants to create a transaction? Or is it just the fact the p2p messages to broadcast a tx aren't implemented on the wallet? Can I create a wallet offline and receive Grin or you must have your wallet running? Maybe those questions should be answered on the docs?

**Comment by KharmaScribbles** [comment]
Your wallet must always have a running Grin node to talk to. 

Since part of the privacy is that there are **no wallet addresses**, to receive Grin you either need to go the document route or have your wallet listening on an HTTP server: [](https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet#via-wallet-listener)

And then the sender would send to you via [](https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet#sending-to-a-running-wallet-listener)

I'm not a programmer, far from it, and this is pretty basic stuff for me.. Learning the command line is a wonderful and powerful skill to have, and really all you need in order to use Grin :)
